name: Main Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, test and publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore
        run: dotnet restore      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal        
      - name: Publish
        run: dotnet publish --configuration Release --no-restore      
      - name: Upload Artifact
        with:
          name: BLEazy.Examples
          path: /home/runner/work/BLEazy/BLEazy/BLEazy.Example/bin/Release/netcoreapp3.1/publish
